MarcetPlace/Models/OrderItem.cs
using System.ComponentModel.DataAnnotations;

namespace MarketPlace.Models
{
    public class orderitem
    {
        [Required]
        [Display(Name = "order")]
        public int orderid { get; set; }

        [Required]
        [Display(Name = "product")]
        public int productid { get; set; }

        [Required]
        [Display(Name = "quantity")]
        public int quantity { get; set; }

        public order order { get; set; }
        public product product { get; set; }
    }
}

MarcetPlace/Controllers/OrderItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MarketPlace.Data;
using MarketPlace.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarketPlace.Controllers
{
    public class orderitemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public orderitemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: orderitems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.orderitems.Include(o => o.order).Include(o => o.product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: orderitems/Details/5
        public async Task<IActionResult> Details(int? orderId, int? productId)
        {
            if (orderId == null || productId == null)
            {
                return NotFound();
            }

            var orderItem = await _context.orderitems
                .Include(o => o.order)
                .Include(o => o.product)
                .FirstOrDefaultAsync(m => m.orderid == orderId && m.productid == productId);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // GET: orderitems/Create
        public IActionResult Create()
        {
            ViewData["OrderId"] = new SelectList(_context.orders, "OrderId", "OrderId");
            ViewData["ProductId"] = new SelectList(_context.products, "ProductId", "Name");
            return View();
        }

        // POST: orderitems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,ProductId,Quantity")] orderitem orderItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.orders, "OrderId", "OrderId", orderItem.orderid);
            ViewData["ProductId"] = new SelectList(_context.products, "ProductId", "Name", orderItem.productid);
            return View(orderItem);
        }

        // GET: orderitems/Edit/5
        public async Task<IActionResult> Edit(int? orderId, int? productId)
        {
            if (orderId == null || productId == null)
            {
                return NotFound();
            }

            var orderItem = await _context.orderitems.FindAsync(orderId, productId);
            if (orderItem == null)
            {
                return NotFound();
            }
            ViewData["OrderId"] = new SelectList(_context.orders, "OrderId", "OrderId", orderItem.orderid);
            ViewData["ProductId"] = new SelectList(_context.products, "ProductId", "Name", orderItem.productid);
            return View(orderItem);
        }

        // POST: orderitems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int orderId, int productId, [Bind("OrderId,ProductId,Quantity")] orderitem orderItem)
        {
            if (orderId != orderItem.orderid || productId != orderItem.productid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.orderid, orderItem.productid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.orders, "OrderId", "OrderId", orderItem.orderid);
            ViewData["ProductId"] = new SelectList(_context.products, "ProductId", "Name", orderItem.productid);
            return View(orderItem);
        }

        // GET: orderitems/Delete/5
        public async Task<IActionResult> Delete(int? orderId, int? productId)
        {
            if (orderId == null || productId == null)
            {
                return NotFound();
            }

            var orderItem = await _context.orderitems
                .Include(o => o.order)
                .Include(o => o.product)
                .FirstOrDefaultAsync(m => m.orderid == orderId && m.productid == productId);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: orderitems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int orderId, int productId)
        {
            var orderItem = await _context.orderitems.FindAsync(orderId, productId);
            _context.orderitems.Remove(orderItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderItemExists(int orderId, int productId)
        {
            return _context.orderitems.Any(e => e.orderid == orderId && e.productid == productId);
        }
    }
}

MarcetPlace/Views/OrderItems/Create.cshtml
@model MarketPlace.Models.orderitem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>orderitem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="orderid" class="control-label"></label>
                <select asp-for="orderid" class="form-control" asp-items="ViewBag.orderid"></select>
            </div>
            <div class="form-group">
                <label asp-for="productid" class="control-label"></label>
                <select asp-for="productid" class="form-control" asp-items="ViewBag.productid"></select>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MarcetPlace/Views/OrderItems/Delete.cshtml
@model MarketPlace.Models.orderitem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>orderitem</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.order.orderid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.order.orderid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.product.nameproduct)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.product.nameproduct)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-group">
            <input type="hidden" asp-for="orderid" />
            <input type="hidden" asp-for="productid" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

MarcetPlace/Views/OrderItems/Edit.cshtml
@model MarketPlace.Models.orderitem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>orderitem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="orderid" />
            <input type="hidden" asp-for="productid" />
            <div class="form-group">
                <label asp-for="orderid" class="control-label"></label>
                <select asp-for="orderid" class="form-control" asp-items="ViewBag.orderid"></select>
            </div>
            <div class="form-group">
                <label asp-for="productid" class="control-label"></label>
                <select asp-for="productid" class="form-control" asp-items="ViewBag.productid"></select>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MarcetPlace/Views/OrderItems/Index.cshtml
@model IEnumerable<MarketPlace.Models.orderitem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a href="@Url.Action("Create", "orderitems")">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.order.orderid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.nameproduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.order.orderid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product.nameproduct)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantity)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-orderid="@item.orderid" asp-route-productid="@item.productid">Edit</a> |
                    <a asp-action="Details" asp-route-orderid="@item.orderid" asp-route-productid="@item.productid">Details</a> |
                    <a asp-action="Delete" asp-route-orderid="@item.orderid" asp-route-productid="@item.productid">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>